### PR TITLE
Feature/view icon toggle

### LINKED ISSUE #36: View Icon for Passwords when Signing Up + Confirm Password Check
## Summary
View toggle to allow users to see or hide the password they enter.

## Problem Statement
Mistyping password when registering leading to redundant password resets or unnecessary new account creation

## Proposed Solution
View Icon toggle and a confirm password input field when signing up

## Additional Context
N.A.

## Acceptance Criteria
- View Icon toggle and a confirm password input field when signing up

## Resources
N.A.

## Dependencies
N.A.

### PR DESCRIPTION
**Pull request by Cheemma1**
I replaced TextInput with Mantine's PasswordInput to enable password visibility toggle and added a confirm password field for registration.

### CODE REVIEW

**Comment by gbudjeakp** [comment]
@Cheemma1  Mind going to the issues page of this PR and commenting that you have worked on it?
I'll add you as the assignee there

**Comment by gbudjeakp** [comment]
@Cheemma1  do you mind providing some screen shots or a gif of the changes and what it looks like

**Comment by Cheemma1** [comment]
Here @gbudjeakp Password Visibility Toggle and Confirm Password Field
buildig-u-2

**Review by gbudjeakp — APPROVED** [review]
LGTM!!! Approving. Love the additional confirmation bit you added

**Comment by Cheemma1** [comment]
@gbudjeakp Thank you for the approval! I'm glad you like the additional confirmation feature.

**Pull request merged**
